# Generated by Django 6.0.7 on 2026-07-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded photo — automatically compressed and resized on save.', null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a real hero photo — automatically compressed and resized on save.', null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Primary photo — automatically compressed and resized on save.', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_secondary',
            field=models.ImageField(blank=True, help_text='Hover/secondary photo — automatically compressed.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='hero_gradient',
            field=models.CharField(blank=True, help_text='CSS fallback background, used only if no image is uploaded.', max_length=255),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_url',
            field=models.URLField(blank=True, help_text='Fallback: a direct image URL (e.g. Unsplash link), used only if no image is uploaded above.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_gradient',
            field=models.CharField(blank=True, help_text='CSS fallback, used only if no image uploaded.', max_length=255),
        ),
    ]
