# Generated by Django 6.0.7 on 2026-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_blogpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignatureCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Example: Oud Collection, Luxury Perfumes",
                        max_length=120,
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=180)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="signature_collections",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signature Collection",
                "verbose_name_plural": "Signature Collections",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
