# Generated by Django 6.0.7 on 2026-07-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_signaturecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Leave blank for a top-level category. Set this to make it a subcategory (e.g. 'Men's Perfume' with parent 'Perfumes').", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category'),
        ),
    ]
