# Generated by Django 6.0.7 on 2026-07-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_signaturecollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True,
                help_text='Brand name, e.g., "Chanel", "Nike"',
                max_length=100,
            ),
        ),
    ]
