# Generated by Django 6.0.7 on 2026-07-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_category_parent"),
        ("store", "0005_product_brand"),
    ]

    operations = []
