# Generated by Django 6.0.7 on 2026-07-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_0005_category_parent_0005_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]