# Generated by Django 6.0.7 on 2026-07-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Check to display this category in the "Shop by Category" section on the homepage'),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in homepage display (lower numbers appear first)'),
        ),
    ]