# Generated by Django 6.0.7 on 2026-07-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_category_homepage_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="display_order",
        ),
        migrations.RemoveField(
            model_name="category",
            name="show_on_homepage",
        ),
    ]
