# Generated by Django 6.0.7 on 2026-07-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_category_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top_rated',
            field=models.BooleanField(default=False, help_text="Manually tag as Top Rated for the homepage 'Chosen For You' section"),
        ),
    ]
