# Generated by Django 6.0.7 on 2026-07-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_remove_category_display_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_full",
            field=models.TextField(
                blank=True,
                help_text="Full description with rich text support (HTML allowed)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_short",
            field=models.TextField(
                blank=True, help_text="Short description shown in product grid"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fragrance_layers",
            field=models.TextField(
                blank=True,
                help_text="Fragrance evolution description (e.g., 'Opens with citrus, settles to warm amber')",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fragrance_notes_base",
            field=models.CharField(
                blank=True,
                help_text="Base notes (e.g., Sandalwood, Vanilla)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fragrance_notes_middle",
            field=models.CharField(
                blank=True,
                help_text="Middle/Heart notes (e.g., Jasmine, Rose)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fragrance_notes_top",
            field=models.CharField(
                blank=True,
                help_text="Top notes (e.g., Bergamot, Lemon)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="highlights",
            field=models.TextField(
                blank=True,
                help_text="Product highlights as JSON array of objects with icon and text",
            ),
        ),
    ]
