# Generated by Django 6.0.7 on 2026-08-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="otp",
            new_name="accounts_ot_phone_n_2f5907_idx",
            old_name="accounts_otp_phone_idx",
        ),
        migrations.RenameIndex(
            model_name="otp",
            new_name="accounts_ot_verific_dfe2af_idx",
            old_name="accounts_otp_token_idx",
        ),
    ]
