# Generated by Django 6.0.7 on 2026-08-04 03:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_otp_purpose_user_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="otp",
            name="accounts_ot_phone_n_2f5907_idx",
        ),
        migrations.AlterField(
            model_name="otp",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10 digits starting with 97 or 98",
                        regex="^(97|98)\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="otp",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["phone_number", "purpose", "created_at"],
                name="accounts_ot_phone_n_831afe_idx",
            ),
        ),
    ]
