# Generated by Django 6.0.7 on 2026-08-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_verifiedguestphone"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="verifiedguestphone",
            new_name="accounts_ve_phone_n_88f0e9_idx",
            old_name="accounts_ver_phone_number_7b8a9e_idx",
        ),
        migrations.RenameIndex(
            model_name="verifiedguestphone",
            new_name="accounts_ve_expires_877445_idx",
            old_name="accounts_ver_expires_at_5f3d2a_idx",
        ),
        migrations.RenameIndex(
            model_name="verifiedguestphone",
            new_name="accounts_ve_is_acti_88a206_idx",
            old_name="accounts_ver_is_active_d2e1b4_idx",
        ),
    ]
