# Generated by Django 6.0.7 on 2026-08-19 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_otp_status_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="is_used",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="related_order",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="session_key",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="sparrow_message_id",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="sparrow_response_code",
        ),
        migrations.RemoveField(
            model_name="otp",
            name="user_agent",
        ),
        migrations.CreateModel(
            name="PendingSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_data",
                    models.JSONField(
                        help_text="Encrypted JSON data containing user signup information"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 10 digits starting with 97 or 98",
                                regex="^(97|98)\\d{8}$",
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this pending signup expires and should be cleaned up"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this pending signup has been used to create a user",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone_number", "created_at"],
                        name="accounts_pe_phone_n_132454_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_pe_expires_375282_idx"
                    ),
                ],
            },
        ),
    ]
